spring.application.name=demo

server.port=${PORT:8081}

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/squareplanner}
spring.datasource.username=${DB_USERNAME:seu_usuario}
spring.datasource.password=${DB_PASSWORD:sua_senha}

spring.jpa.hibernate.ddl-auto=none

spring.sql.init.mode=always

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true
